Repository nextcloud/terms_of_service, pull requests merged in 2021-04, with the labels that each got.

#508 Move to IBootstrap
  lib/AppInfo/Application.php
  lib/Listener/UserDeletedListener.php
Labels: 3. to review, backport-request, technical debt

#487 Sabre plugin to return informative message if ToS are not signed
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Checker.php
  lib/Dav/CheckPlugin.php
Labels: 3. to review, enhancement

#511 Registration integration
  Makefile
  js/terms_of_service_admin.js
  js/terms_of_service_admin.js.map
  js/terms_of_service_public.js
  js/terms_of_service_public.js.map
  js/terms_of_service_registration.js
  js/terms_of_service_registration.js.map
  js/terms_of_service_user.js
  js/terms_of_service_user.js.map
  lib/AppInfo/Application.php
  lib/Db/Mapper/SignatoryMapper.php
  lib/Listener/RegistrationIntegration.php
  package-lock.json
  src/Registration.vue
  src/UserApp.vue
  src/registration.js
  webpack.js
Labels: 3. to review, enhancement

#517 Dont update dependencies on install
  Makefile
Labels: 3. to review, backport-request, technical debt

#521 [stable21] Registration integration
  Makefile
  js/terms_of_service_admin.js
  js/terms_of_service_admin.js.map
  js/terms_of_service_public.js
  js/terms_of_service_public.js.map
  js/terms_of_service_registration.js
  js/terms_of_service_registration.js.map
  js/terms_of_service_user.js
  js/terms_of_service_user.js.map
  lib/AppInfo/Application.php
  lib/Db/Mapper/SignatoryMapper.php
  lib/Listener/RegistrationIntegration.php
  package-lock.json
  src/Registration.vue
  src/UserApp.vue
  src/registration.js
  webpack.js
Labels: 3. to review

#522 Fix language selector on public page
  css/overlay.scss
  lib/Listener/RegistrationIntegration.php
Labels: 3. to review, backport-request, bug

#524 Add changelog for 1.7.0
  CHANGELOG.md
Labels: 3. to review

#532 Fix a-color on registration form
  css/overlay.scss
Labels: 3. to review, bug

#534 Move to new webpack config
  babel.config.js
  js/terms_of_service_admin.js
  js/terms_of_service_admin.js.LICENSE.txt
  js/terms_of_service_admin.js.map
  js/terms_of_service_public.js
  js/terms_of_service_public.js.LICENSE.txt
  js/terms_of_service_public.js.map
  js/terms_of_service_registration.js
  js/terms_of_service_registration.js.LICENSE.txt
  js/terms_of_service_registration.js.map
  js/terms_of_service_user.js
  js/terms_of_service_user.js.LICENSE.txt
  js/terms_of_service_user.js.map
  package-lock.json
  package.json
  webpack.js
Labels: 3. to review, technical debt
