Repository nextcloud/terms_of_service, pull requests merged in 2021-12, with the labels that each got.

#649 Add index for performance
  appinfo/info.xml
  lib/Migration/Version1000Date20211209135602.php
Labels: 3. to review, enhancement

#650 Add tos_sigs_terms_id index
  lib/Migration/Version1000Date20211209135602.php
Labels: 4. to release, enhancement

#654 Make migration re-runable
  lib/Migration/Version1000Date20211209135602.php
Labels: 3. to review, bug

#657 Downgrade vue js modal again
  css/overlay.scss
  js/terms_of_service-public.js
  js/terms_of_service-public.js.map
  js/terms_of_service-registration.js
  js/terms_of_service-registration.js.map
  js/terms_of_service-user.js
  js/terms_of_service-user.js.map
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug, high, regression

#659 Use new modal component
  css/overlay.scss
  js/terms_of_service-public.js
  js/terms_of_service-public.js.LICENSE.txt
  js/terms_of_service-public.js.map
  js/terms_of_service-registration.js
  js/terms_of_service-registration.js.LICENSE.txt
  js/terms_of_service-registration.js.map
  js/terms_of_service-user.js
  js/terms_of_service-user.js.LICENSE.txt
  js/terms_of_service-user.js.map
  package-lock.json
  package.json
  src/Registration.vue
  src/UserApp.vue
  src/components/ModalContent.vue
  src/public.js
  src/registration.js
  src/user.js
Labels: 3. to review, technical debt
