Repository nextcloud/terms_of_service, pull requests merged in 2022-10, with the labels that each got.

#758 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#759 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#760 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
  .github/workflows/node.yml
Labels: dependencies

#761 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#763 Allow changing the settings from UI
  js/terms_of_service-admin.js
  js/terms_of_service-admin.js.LICENSE.txt
  js/terms_of_service-admin.js.map
  lib/Controller/TermsController.php
  lib/Settings/Admin.php
  lib/Settings/AdminSection.php
  package-lock.json
  package.json
  src/App.vue
  src/components/Term.vue
Labels: 3. to review, enhancement

#765 Allow WOPI requests from the richdocuments/Collabora integration
  lib/Checker.php
Labels: 3. to review, bug
