Repository nextcloud/terms_of_service, pull requests merged in 2022-01, with the labels that each got.

#671 [stable23] 1.9.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#673 [stable21] 1.7.4
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review

#672 [stable22] 1.8.4
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review

#677 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#680 Update workflows from template repository
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: backport-request
