Repository nextcloud/terms_of_service, pull requests merged in 2022-03, with the labels that each got.

#691 Handle IP addresses which only return a continent, not a country
  lib/CountryDetector.php
Labels: 3. to review, backport-request, bug

#697 Add changelog for 1.7.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#696 Add changelog for 1.8.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#695 Add changelog for 1.9.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#702 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#701 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#700 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#699 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#705 Exit earlier if no terms have to be accepted
  lib/Checker.php
Labels: 3. to review, backport-request, bug

#706 Get country terms and global terms in 1 query
  lib/Db/Mapper/TermsMapper.php
Labels: 3. to review, enhancement
