Repository nextcloud/terms_of_service, pull requests merged in 2024-12, with the labels that each got.

#1021 [stable27] feat: improve save terms and reset signaturies actions
  js/terms_of_service-admin.js
  js/terms_of_service-admin.js.map
  src/App.vue
Labels: 3. to review

#1022 release v4.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1026 fix(l10n): Fix typo in translation
  js/terms_of_service-admin.js
  js/terms_of_service-admin.js.map
  src/App.vue
Labels: 3. to review, backport-request, bug

#1025 chore(i18n): Improved grammar
  js/terms_of_service-admin.js
  js/terms_of_service-admin.js.map
  src/App.vue
Labels: backport-request

#1030 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
