Repository nextcloud/terms_of_service, pull requests merged in 2024-10, with the labels that each got.

#1002 release 3.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#1004 ci(psalm): Add psalm CI
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/psalm-matrix.yml
  .gitignore
  appinfo/info.xml
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Checker.php
  lib/Db/Mapper/SignatoryMapper.php
  lib/Db/Mapper/TermsMapper.php
  lib/Filesystem/CacheWrapper.php
  lib/Listener/RegistrationIntegration.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version1000Date20220111180247.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/psalm-baseline.xml.license
  tests/stubs/filesystem.php
  tests/stubs/registration.php
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, bug

#1009 fix(notifications): Rework the notification handling
  appinfo/info.xml
  lib/BackgroundJobs/CreateNotifications.php
  lib/Controller/SigningController.php
  lib/Controller/TermsController.php
  lib/Db/Mapper/SignatoryMapper.php
  lib/Migration/CreateNotifications.php
Labels: 3. to review, backport-request, bug

#1011 Add OpenAPI docs
  .github/workflows/openapi.yml
  REUSE.toml
  appinfo/routes.php
  composer.json
  lib/Controller/SigningController.php
  lib/Controller/TermsController.php
  lib/Db/Entities/Terms.php
  lib/Db/Mapper/CountryMapper.php
  lib/Db/Mapper/LanguageMapper.php
  lib/Db/Mapper/TermsMapper.php
  lib/ResponseDefinitions.php
  openapi-administration.json
  openapi-full.json
  openapi.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, enhancement
