Repository nextcloud/terms_of_service, pull requests merged in 2024-02, with the labels that each got.

#907 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review, dependencies, automated

#913 Release v2.4.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#911 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies
