Repository nextcloud/terms_of_service, pull requests merged in 2025-02, with the labels that each got.

#1045 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1046 fix: show ToS on non-files public pages (calendar/collectives/talk), Files on Nextcloud 31 and Login-flow
  js/terms_of_service-public.js
  js/terms_of_service-public.js.map
  lib/AppInfo/Application.php
  package-lock.json
  package.json
  src/public.js
Labels: 3. to review, bug

#1048 ci(psalm): Require PHP 8.3 for now as 8.4 does not work with 5.6 of p…
  .github/workflows/psalm-matrix.yml
Labels: 3. to review

#1051 release v3.4.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
